# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AxiomaEquityOptimizationParameters
#' @description AxiomaEquityOptimizationParameters Class
#' @format An \code{R6Class} generator object
#' @field strategy  \link{OptimizerStrategy} 
#'
#' @field account  \link{OptimizerAccount} [optional]
#'
#' @field optimization  \link{Optimization} [optional]
#'
#' @field outputtypes  \link{OptimizerOutputTypes} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AxiomaEquityOptimizationParameters <- R6::R6Class(
  'AxiomaEquityOptimizationParameters',
  public = list(
    `strategy` = NULL,
    `account` = NULL,
    `optimization` = NULL,
    `outputtypes` = NULL,
    initialize = function(`strategy`, `outputtypes`, `account`=NULL, `optimization`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`strategy`)) {
        stopifnot(R6::is.R6(`strategy`))
        self$`strategy` <- `strategy`
      }
      if (!missing(`outputtypes`)) {
        stopifnot(R6::is.R6(`outputtypes`))
        self$`outputtypes` <- `outputtypes`
      }
      if (!is.null(`account`)) {
        stopifnot(R6::is.R6(`account`))
        self$`account` <- `account`
      }
      if (!is.null(`optimization`)) {
        stopifnot(R6::is.R6(`optimization`))
        self$`optimization` <- `optimization`
      }
    },
    toJSON = function() {
      AxiomaEquityOptimizationParametersObject <- list()
      if (!is.null(self$`strategy`)) {
        AxiomaEquityOptimizationParametersObject[['strategy']] <-
          self$`strategy`$toJSON()
      }
      if (!is.null(self$`account`)) {
        AxiomaEquityOptimizationParametersObject[['account']] <-
          self$`account`$toJSON()
      }
      if (!is.null(self$`optimization`)) {
        AxiomaEquityOptimizationParametersObject[['optimization']] <-
          self$`optimization`$toJSON()
      }
      if (!is.null(self$`outputtypes`)) {
        AxiomaEquityOptimizationParametersObject[['outputtypes']] <-
          self$`outputtypes`$toJSON()
      }

      AxiomaEquityOptimizationParametersObject
    },
    fromJSON = function(AxiomaEquityOptimizationParametersJson) {
      AxiomaEquityOptimizationParametersObject <- jsonlite::fromJSON(AxiomaEquityOptimizationParametersJson)
      if (!is.null(AxiomaEquityOptimizationParametersObject$`strategy`)) {
        strategyObject <- OptimizerStrategy$new()
        strategyObject$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$strategy, auto_unbox = TRUE, digits = NA))
        self$`strategy` <- strategyObject
      }
      if (!is.null(AxiomaEquityOptimizationParametersObject$`account`)) {
        accountObject <- OptimizerAccount$new()
        accountObject$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$account, auto_unbox = TRUE, digits = NA))
        self$`account` <- accountObject
      }
      if (!is.null(AxiomaEquityOptimizationParametersObject$`optimization`)) {
        optimizationObject <- Optimization$new()
        optimizationObject$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$optimization, auto_unbox = TRUE, digits = NA))
        self$`optimization` <- optimizationObject
      }
      if (!is.null(AxiomaEquityOptimizationParametersObject$`outputtypes`)) {
        outputtypesObject <- OptimizerOutputTypes$new()
        outputtypesObject$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$outputtypes, auto_unbox = TRUE, digits = NA))
        self$`outputtypes` <- outputtypesObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`strategy`)) {
        sprintf(
        '"strategy":
        %s
        ',
        jsonlite::toJSON(self$`strategy`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
        %s
        ',
        jsonlite::toJSON(self$`account`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`optimization`)) {
        sprintf(
        '"optimization":
        %s
        ',
        jsonlite::toJSON(self$`optimization`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`outputtypes`)) {
        sprintf(
        '"outputtypes":
        %s
        ',
        jsonlite::toJSON(self$`outputtypes`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AxiomaEquityOptimizationParametersJson) {
      AxiomaEquityOptimizationParametersObject <- jsonlite::fromJSON(AxiomaEquityOptimizationParametersJson)
      self$`strategy` <- OptimizerStrategy$new()$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$strategy, auto_unbox = TRUE, digits = NA))
      self$`account` <- OptimizerAccount$new()$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$account, auto_unbox = TRUE, digits = NA))
      self$`optimization` <- Optimization$new()$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$optimization, auto_unbox = TRUE, digits = NA))
      self$`outputtypes` <- OptimizerOutputTypes$new()$fromJSON(jsonlite::toJSON(AxiomaEquityOptimizationParametersObject$outputtypes, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
