# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CalculationMeta
#' @description CalculationMeta Class
#' @format An \code{R6Class} generator object
#' @field contentorganization  character [optional]
#'
#' @field contenttype  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CalculationMeta <- R6::R6Class(
  'CalculationMeta',
  public = list(
    `contentorganization` = NULL,
    `contenttype` = NULL,
    initialize = function(`contentorganization`='SimplifiedRow', `contenttype`='Json', ...){
      local.optional.var <- list(...)
      if (!is.null(`contentorganization`)) {
        stopifnot(is.character(`contentorganization`), length(`contentorganization`) == 1)
        self$`contentorganization` <- `contentorganization`
      }
      if (!is.null(`contenttype`)) {
        stopifnot(is.character(`contenttype`), length(`contenttype`) == 1)
        self$`contenttype` <- `contenttype`
      }
    },
    toJSON = function() {
      CalculationMetaObject <- list()
      if (!is.null(self$`contentorganization`)) {
        CalculationMetaObject[['contentorganization']] <-
          self$`contentorganization`
      }
      if (!is.null(self$`contenttype`)) {
        CalculationMetaObject[['contenttype']] <-
          self$`contenttype`
      }

      CalculationMetaObject
    },
    fromJSON = function(CalculationMetaJson) {
      CalculationMetaObject <- jsonlite::fromJSON(CalculationMetaJson)
      if (!is.null(CalculationMetaObject$`contentorganization`)) {
        self$`contentorganization` <- CalculationMetaObject$`contentorganization`
      }
      if (!is.null(CalculationMetaObject$`contenttype`)) {
        self$`contenttype` <- CalculationMetaObject$`contenttype`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`contentorganization`)) {
        sprintf(
        '"contentorganization":
          "%s"
                ',
        self$`contentorganization`
        )},
        if (!is.null(self$`contenttype`)) {
        sprintf(
        '"contenttype":
          "%s"
                ',
        self$`contenttype`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CalculationMetaJson) {
      CalculationMetaObject <- jsonlite::fromJSON(CalculationMetaJson)
      self$`contentorganization` <- CalculationMetaObject$`contentorganization`
      self$`contenttype` <- CalculationMetaObject$`contenttype`
      self
    }
  )
)
