# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CalculationStatus
#' @description CalculationStatus Class
#' @format An \code{R6Class} generator object
#' @field calculationid  character [optional]
#'
#' @field status  character [optional]
#'
#' @field units  named list( \link{CalculationUnitStatus} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CalculationStatus <- R6::R6Class(
  'CalculationStatus',
  public = list(
    `calculationid` = NULL,
    `status` = NULL,
    `units` = NULL,
    initialize = function(`calculationid`=NULL, `status`=NULL, `units`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`calculationid`)) {
        stopifnot(is.character(`calculationid`), length(`calculationid`) == 1)
        self$`calculationid` <- `calculationid`
      }
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`units`)) {
        stopifnot(is.vector(`units`), length(`units`) != 0)
        sapply(`units`, function(x) stopifnot(R6::is.R6(x)))
        self$`units` <- `units`
      }
    },
    toJSON = function() {
      CalculationStatusObject <- list()
      if (!is.null(self$`calculationid`)) {
        CalculationStatusObject[['calculationid']] <-
          self$`calculationid`
      }
      if (!is.null(self$`status`)) {
        CalculationStatusObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`units`)) {
        CalculationStatusObject[['units']] <-
          lapply(self$`units`, function(x) x$toJSON())
      }

      CalculationStatusObject
    },
    fromJSON = function(CalculationStatusJson) {
      CalculationStatusObject <- jsonlite::fromJSON(CalculationStatusJson)
      if (!is.null(CalculationStatusObject$`calculationid`)) {
        self$`calculationid` <- CalculationStatusObject$`calculationid`
      }
      if (!is.null(CalculationStatusObject$`status`)) {
        self$`status` <- CalculationStatusObject$`status`
      }
      if (!is.null(CalculationStatusObject$`units`)) {
        self$`units` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`units`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`calculationid`)) {
        sprintf(
        '"calculationid":
          "%s"
                ',
        self$`calculationid`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`units`)) {
        sprintf(
        '"units":
        %s
',
        jsonlite::toJSON(lapply(self$`units`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CalculationStatusJson) {
      CalculationStatusObject <- jsonlite::fromJSON(CalculationStatusJson)
      self$`calculationid` <- CalculationStatusObject$`calculationid`
      self$`status` <- CalculationStatusObject$`status`
      self$`units` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`units`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
