# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CalculationStatus
#' @description CalculationStatus Class
#' @format An \code{R6Class} generator object
#' @field status  character [optional]
#'
#' @field units  integer [optional]
#'
#' @field pa  named list( \link{CalculationUnitStatus} ) [optional]
#'
#' @field spar  named list( \link{CalculationUnitStatus} ) [optional]
#'
#' @field vault  named list( \link{CalculationUnitStatus} ) [optional]
#'
#' @field pub  named list( \link{CalculationUnitStatus} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CalculationStatus <- R6::R6Class(
  'CalculationStatus',
  public = list(
    `status` = NULL,
    `units` = NULL,
    `pa` = NULL,
    `spar` = NULL,
    `vault` = NULL,
    `pub` = NULL,
    initialize = function(`status`=NULL, `units`=NULL, `pa`=NULL, `spar`=NULL, `vault`=NULL, `pub`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`units`)) {
        stopifnot(is.numeric(`units`), length(`units`) == 1)
        self$`units` <- `units`
      }
      if (!is.null(`pa`)) {
        stopifnot(is.vector(`pa`), length(`pa`) != 0)
        sapply(`pa`, function(x) stopifnot(R6::is.R6(x)))
        self$`pa` <- `pa`
      }
      if (!is.null(`spar`)) {
        stopifnot(is.vector(`spar`), length(`spar`) != 0)
        sapply(`spar`, function(x) stopifnot(R6::is.R6(x)))
        self$`spar` <- `spar`
      }
      if (!is.null(`vault`)) {
        stopifnot(is.vector(`vault`), length(`vault`) != 0)
        sapply(`vault`, function(x) stopifnot(R6::is.R6(x)))
        self$`vault` <- `vault`
      }
      if (!is.null(`pub`)) {
        stopifnot(is.vector(`pub`), length(`pub`) != 0)
        sapply(`pub`, function(x) stopifnot(R6::is.R6(x)))
        self$`pub` <- `pub`
      }
    },
    toJSON = function() {
      CalculationStatusObject <- list()
      if (!is.null(self$`status`)) {
        CalculationStatusObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`units`)) {
        CalculationStatusObject[['units']] <-
          self$`units`
      }
      if (!is.null(self$`pa`)) {
        CalculationStatusObject[['pa']] <-
          lapply(self$`pa`, function(x) x$toJSON())
      }
      if (!is.null(self$`spar`)) {
        CalculationStatusObject[['spar']] <-
          lapply(self$`spar`, function(x) x$toJSON())
      }
      if (!is.null(self$`vault`)) {
        CalculationStatusObject[['vault']] <-
          lapply(self$`vault`, function(x) x$toJSON())
      }
      if (!is.null(self$`pub`)) {
        CalculationStatusObject[['pub']] <-
          lapply(self$`pub`, function(x) x$toJSON())
      }

      CalculationStatusObject
    },
    fromJSON = function(CalculationStatusJson) {
      CalculationStatusObject <- jsonlite::fromJSON(CalculationStatusJson)
      if (!is.null(CalculationStatusObject$`status`)) {
        self$`status` <- CalculationStatusObject$`status`
      }
      if (!is.null(CalculationStatusObject$`units`)) {
        self$`units` <- CalculationStatusObject$`units`
      }
      if (!is.null(CalculationStatusObject$`pa`)) {
        self$`pa` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`pa`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(CalculationStatusObject$`spar`)) {
        self$`spar` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`spar`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(CalculationStatusObject$`vault`)) {
        self$`vault` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`vault`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(CalculationStatusObject$`pub`)) {
        self$`pub` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`pub`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`units`)) {
        sprintf(
        '"units":
          %d
                ',
        self$`units`
        )},
        if (!is.null(self$`pa`)) {
        sprintf(
        '"pa":
        %s
',
        jsonlite::toJSON(lapply(self$`pa`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`spar`)) {
        sprintf(
        '"spar":
        %s
',
        jsonlite::toJSON(lapply(self$`spar`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`vault`)) {
        sprintf(
        '"vault":
        %s
',
        jsonlite::toJSON(lapply(self$`vault`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`pub`)) {
        sprintf(
        '"pub":
        %s
',
        jsonlite::toJSON(lapply(self$`pub`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CalculationStatusJson) {
      CalculationStatusObject <- jsonlite::fromJSON(CalculationStatusJson)
      self$`status` <- CalculationStatusObject$`status`
      self$`units` <- CalculationStatusObject$`units`
      self$`pa` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`pa`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      self$`spar` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`spar`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      self$`vault` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`vault`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      self$`pub` <- ApiClient$new()$deserializeObj(CalculationStatusObject$`pub`, "map(CalculationUnitStatus)", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
