# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CalculationInfo
#' @description CalculationInfo Class
#' @format An \code{R6Class} generator object
#' @field id  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CalculationInfo <- R6::R6Class(
  'CalculationInfo',
  public = list(
    `id` = NULL,
    initialize = function(`id`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      CalculationInfoObject <- list()
      if (!is.null(self$`id`)) {
        CalculationInfoObject[['id']] <-
          self$`id`
      }

      CalculationInfoObject
    },
    fromJSON = function(CalculationInfoJson) {
      CalculationInfoObject <- jsonlite::fromJSON(CalculationInfoJson)
      if (!is.null(CalculationInfoObject$`id`)) {
        self$`id` <- CalculationInfoObject$`id`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CalculationInfoJson) {
      CalculationInfoObject <- jsonlite::fromJSON(CalculationInfoJson)
      self$`id` <- CalculationInfoObject$`id`
      self
    }
  )
)
