# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ClientErrorResponse
#' @description ClientErrorResponse Class
#' @format An \code{R6Class} generator object
#' @field errors  list( \link{Error} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ClientErrorResponse <- R6::R6Class(
  'ClientErrorResponse',
  public = list(
    `errors` = NULL,
    initialize = function(`errors`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`), length(`errors`) != 0)
        sapply(`errors`, function(x) stopifnot(R6::is.R6(x)))
        self$`errors` <- `errors`
      }
    },
    toJSON = function() {
      ClientErrorResponseObject <- list()
      if (!is.null(self$`errors`)) {
        ClientErrorResponseObject[['errors']] <-
          lapply(self$`errors`, function(x) x$toJSON())
      }

      ClientErrorResponseObject
    },
    fromJSON = function(ClientErrorResponseJson) {
      ClientErrorResponseObject <- jsonlite::fromJSON(ClientErrorResponseJson)
      if (!is.null(ClientErrorResponseObject$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(ClientErrorResponseObject$`errors`, "array[Error]", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`errors`)) {
        sprintf(
        '"errors":
        [%s]
',
        paste(sapply(self$`errors`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ClientErrorResponseJson) {
      ClientErrorResponseObject <- jsonlite::fromJSON(ClientErrorResponseJson)
      self$`errors` <- ApiClient$new()$deserializeObj(ClientErrorResponseObject$`errors`, "array[Error]", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
