# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ColumnStatisticRoot
#' @description ColumnStatisticRoot Class
#' @format An \code{R6Class} generator object
#' @field data  named list( \link{ColumnStatistic} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ColumnStatisticRoot <- R6::R6Class(
  'ColumnStatisticRoot',
  public = list(
    `data` = NULL,
    initialize = function(`data`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      ColumnStatisticRootObject <- list()
      if (!is.null(self$`data`)) {
        ColumnStatisticRootObject[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }

      ColumnStatisticRootObject
    },
    fromJSON = function(ColumnStatisticRootJson) {
      ColumnStatisticRootObject <- jsonlite::fromJSON(ColumnStatisticRootJson)
      if (!is.null(ColumnStatisticRootObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(ColumnStatisticRootObject$`data`, "map(ColumnStatistic)", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
',
        jsonlite::toJSON(lapply(self$`data`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ColumnStatisticRootJson) {
      ColumnStatisticRootObject <- jsonlite::fromJSON(ColumnStatisticRootJson)
      self$`data` <- ApiClient$new()$deserializeObj(ColumnStatisticRootObject$`data`, "map(ColumnStatistic)", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
