# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FICalculationParameters
#' @description FICalculationParameters Class
#' @format An \code{R6Class} generator object
#' @field securities  list( \link{FISecurity} ) 
#'
#' @field calculations  list( character ) 
#'
#' @field jobSettings  \link{FIJobSettings} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FICalculationParameters <- R6::R6Class(
  'FICalculationParameters',
  public = list(
    `securities` = NULL,
    `calculations` = NULL,
    `jobSettings` = NULL,
    initialize = function(`securities`, `calculations`, `jobSettings`, ...){
      local.optional.var <- list(...)
      if (!missing(`securities`)) {
        stopifnot(is.vector(`securities`), length(`securities`) != 0)
        sapply(`securities`, function(x) stopifnot(R6::is.R6(x)))
        self$`securities` <- `securities`
      }
      if (!missing(`calculations`)) {
        stopifnot(is.vector(`calculations`), length(`calculations`) != 0)
        sapply(`calculations`, function(x) stopifnot(is.character(x)))
        self$`calculations` <- `calculations`
      }
      if (!missing(`jobSettings`)) {
        stopifnot(R6::is.R6(`jobSettings`))
        self$`jobSettings` <- `jobSettings`
      }
    },
    toJSON = function() {
      FICalculationParametersObject <- list()
      if (!is.null(self$`securities`)) {
        FICalculationParametersObject[['securities']] <-
          lapply(self$`securities`, function(x) x$toJSON())
      }
      if (!is.null(self$`calculations`)) {
        FICalculationParametersObject[['calculations']] <-
          self$`calculations`
      }
      if (!is.null(self$`jobSettings`)) {
        FICalculationParametersObject[['jobSettings']] <-
          self$`jobSettings`$toJSON()
      }

      FICalculationParametersObject
    },
    fromJSON = function(FICalculationParametersJson) {
      FICalculationParametersObject <- jsonlite::fromJSON(FICalculationParametersJson)
      if (!is.null(FICalculationParametersObject$`securities`)) {
        self$`securities` <- ApiClient$new()$deserializeObj(FICalculationParametersObject$`securities`, "array[FISecurity]", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(FICalculationParametersObject$`calculations`)) {
        self$`calculations` <- ApiClient$new()$deserializeObj(FICalculationParametersObject$`calculations`, "array[character]", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(FICalculationParametersObject$`jobSettings`)) {
        jobSettingsObject <- FIJobSettings$new()
        jobSettingsObject$fromJSON(jsonlite::toJSON(FICalculationParametersObject$jobSettings, auto_unbox = TRUE, digits = NA))
        self$`jobSettings` <- jobSettingsObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`securities`)) {
        sprintf(
        '"securities":
        [%s]
',
        paste(sapply(self$`securities`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`calculations`)) {
        sprintf(
        '"calculations":
           [%s]
        ',
        paste(unlist(lapply(self$`calculations`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`jobSettings`)) {
        sprintf(
        '"jobSettings":
        %s
        ',
        jsonlite::toJSON(self$`jobSettings`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FICalculationParametersJson) {
      FICalculationParametersObject <- jsonlite::fromJSON(FICalculationParametersJson)
      self$`securities` <- ApiClient$new()$deserializeObj(FICalculationParametersObject$`securities`, "array[FISecurity]", loadNamespace("factset.analyticsapi.engines"))
      self$`calculations` <- ApiClient$new()$deserializeObj(FICalculationParametersObject$`calculations`, "array[character]", loadNamespace("factset.analyticsapi.engines"))
      self$`jobSettings` <- FIJobSettings$new()$fromJSON(jsonlite::toJSON(FICalculationParametersObject$jobSettings, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
