# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FICalculationParametersRoot
#' @description FICalculationParametersRoot Class
#' @format An \code{R6Class} generator object
#' @field data  \link{FICalculationParameters} [optional]
#'
#' @field meta  \link{CalculationMeta} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FICalculationParametersRoot <- R6::R6Class(
  'FICalculationParametersRoot',
  public = list(
    `data` = NULL,
    `meta` = NULL,
    initialize = function(`data`=NULL, `meta`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
      if (!is.null(`meta`)) {
        stopifnot(R6::is.R6(`meta`))
        self$`meta` <- `meta`
      }
    },
    toJSON = function() {
      FICalculationParametersRootObject <- list()
      if (!is.null(self$`data`)) {
        FICalculationParametersRootObject[['data']] <-
          self$`data`$toJSON()
      }
      if (!is.null(self$`meta`)) {
        FICalculationParametersRootObject[['meta']] <-
          self$`meta`$toJSON()
      }

      FICalculationParametersRootObject
    },
    fromJSON = function(FICalculationParametersRootJson) {
      FICalculationParametersRootObject <- jsonlite::fromJSON(FICalculationParametersRootJson)
      if (!is.null(FICalculationParametersRootObject$`data`)) {
        dataObject <- FICalculationParameters$new()
        dataObject$fromJSON(jsonlite::toJSON(FICalculationParametersRootObject$data, auto_unbox = TRUE, digits = NA))
        self$`data` <- dataObject
      }
      if (!is.null(FICalculationParametersRootObject$`meta`)) {
        metaObject <- CalculationMeta$new()
        metaObject$fromJSON(jsonlite::toJSON(FICalculationParametersRootObject$meta, auto_unbox = TRUE, digits = NA))
        self$`meta` <- metaObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
        ',
        jsonlite::toJSON(self$`data`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
        %s
        ',
        jsonlite::toJSON(self$`meta`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FICalculationParametersRootJson) {
      FICalculationParametersRootObject <- jsonlite::fromJSON(FICalculationParametersRootJson)
      self$`data` <- FICalculationParameters$new()$fromJSON(jsonlite::toJSON(FICalculationParametersRootObject$data, auto_unbox = TRUE, digits = NA))
      self$`meta` <- CalculationMeta$new()$fromJSON(jsonlite::toJSON(FICalculationParametersRootObject$meta, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
