# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FIJobSettings
#' @description FIJobSettings Class
#' @format An \code{R6Class} generator object
#' @field asOfDate  character 
#'
#' @field partialDurationMonths  list( integer ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FIJobSettings <- R6::R6Class(
  'FIJobSettings',
  public = list(
    `asOfDate` = NULL,
    `partialDurationMonths` = NULL,
    initialize = function(`asOfDate`, `partialDurationMonths`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`asOfDate`)) {
        stopifnot(is.character(`asOfDate`), length(`asOfDate`) == 1)
        self$`asOfDate` <- `asOfDate`
      }
      if (!is.null(`partialDurationMonths`)) {
        stopifnot(is.vector(`partialDurationMonths`), length(`partialDurationMonths`) != 0)
        sapply(`partialDurationMonths`, function(x) stopifnot(is.character(x)))
        self$`partialDurationMonths` <- `partialDurationMonths`
      }
    },
    toJSON = function() {
      FIJobSettingsObject <- list()
      if (!is.null(self$`asOfDate`)) {
        FIJobSettingsObject[['asOfDate']] <-
          self$`asOfDate`
      }
      if (!is.null(self$`partialDurationMonths`)) {
        FIJobSettingsObject[['partialDurationMonths']] <-
          self$`partialDurationMonths`
      }

      FIJobSettingsObject
    },
    fromJSON = function(FIJobSettingsJson) {
      FIJobSettingsObject <- jsonlite::fromJSON(FIJobSettingsJson)
      if (!is.null(FIJobSettingsObject$`asOfDate`)) {
        self$`asOfDate` <- FIJobSettingsObject$`asOfDate`
      }
      if (!is.null(FIJobSettingsObject$`partialDurationMonths`)) {
        self$`partialDurationMonths` <- ApiClient$new()$deserializeObj(FIJobSettingsObject$`partialDurationMonths`, "array[integer]", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`asOfDate`)) {
        sprintf(
        '"asOfDate":
          "%s"
                ',
        self$`asOfDate`
        )},
        if (!is.null(self$`partialDurationMonths`)) {
        sprintf(
        '"partialDurationMonths":
           [%s]
        ',
        paste(unlist(lapply(self$`partialDurationMonths`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FIJobSettingsJson) {
      FIJobSettingsObject <- jsonlite::fromJSON(FIJobSettingsJson)
      self$`asOfDate` <- FIJobSettingsObject$`asOfDate`
      self$`partialDurationMonths` <- ApiClient$new()$deserializeObj(FIJobSettingsObject$`partialDurationMonths`, "array[integer]", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
