# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FIABCalculationStatusSummary
#' @description FIABCalculationStatusSummary Class
#' @format An \code{R6Class} generator object
#' @field requesttime  character [optional]
#'
#' @field lastpolltime  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FIABCalculationStatusSummary <- R6::R6Class(
  'FIABCalculationStatusSummary',
  public = list(
    `requesttime` = NULL,
    `lastpolltime` = NULL,
    initialize = function(`requesttime`=NULL, `lastpolltime`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`requesttime`)) {
        stopifnot(is.character(`requesttime`), length(`requesttime`) == 1)
        self$`requesttime` <- `requesttime`
      }
      if (!is.null(`lastpolltime`)) {
        stopifnot(is.character(`lastpolltime`), length(`lastpolltime`) == 1)
        self$`lastpolltime` <- `lastpolltime`
      }
    },
    toJSON = function() {
      FIABCalculationStatusSummaryObject <- list()
      if (!is.null(self$`requesttime`)) {
        FIABCalculationStatusSummaryObject[['requesttime']] <-
          self$`requesttime`
      }
      if (!is.null(self$`lastpolltime`)) {
        FIABCalculationStatusSummaryObject[['lastpolltime']] <-
          self$`lastpolltime`
      }

      FIABCalculationStatusSummaryObject
    },
    fromJSON = function(FIABCalculationStatusSummaryJson) {
      FIABCalculationStatusSummaryObject <- jsonlite::fromJSON(FIABCalculationStatusSummaryJson)
      if (!is.null(FIABCalculationStatusSummaryObject$`requesttime`)) {
        self$`requesttime` <- FIABCalculationStatusSummaryObject$`requesttime`
      }
      if (!is.null(FIABCalculationStatusSummaryObject$`lastpolltime`)) {
        self$`lastpolltime` <- FIABCalculationStatusSummaryObject$`lastpolltime`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`requesttime`)) {
        sprintf(
        '"requesttime":
          "%s"
                ',
        self$`requesttime`
        )},
        if (!is.null(self$`lastpolltime`)) {
        sprintf(
        '"lastpolltime":
          "%s"
                ',
        self$`lastpolltime`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FIABCalculationStatusSummaryJson) {
      FIABCalculationStatusSummaryObject <- jsonlite::fromJSON(FIABCalculationStatusSummaryJson)
      self$`requesttime` <- FIABCalculationStatusSummaryObject$`requesttime`
      self$`lastpolltime` <- FIABCalculationStatusSummaryObject$`lastpolltime`
      self
    }
  )
)
