# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FIABIdentifier
#' @description FIABIdentifier Class
#' @format An \code{R6Class} generator object
#' @field id  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FIABIdentifier <- R6::R6Class(
  'FIABIdentifier',
  public = list(
    `id` = NULL,
    initialize = function(`id`, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      FIABIdentifierObject <- list()
      if (!is.null(self$`id`)) {
        FIABIdentifierObject[['id']] <-
          self$`id`
      }

      FIABIdentifierObject
    },
    fromJSON = function(FIABIdentifierJson) {
      FIABIdentifierObject <- jsonlite::fromJSON(FIABIdentifierJson)
      if (!is.null(FIABIdentifierObject$`id`)) {
        self$`id` <- FIABIdentifierObject$`id`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FIABIdentifierJson) {
      FIABIdentifierObject <- jsonlite::fromJSON(FIABIdentifierJson)
      self$`id` <- FIABIdentifierObject$`id`
      self
    }
  )
)
