# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FIABCalculationStatus
#' @description FIABCalculationStatus Class
#' @format An \code{R6Class} generator object
#' @field id  character [optional]
#'
#' @field status  character [optional]
#'
#' @field startdatetime  character [optional]
#'
#' @field completiondatetime  character [optional]
#'
#' @field progress  integer [optional]
#'
#' @field batchevents  list( \link{EventSummary} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FIABCalculationStatus <- R6::R6Class(
  'FIABCalculationStatus',
  public = list(
    `id` = NULL,
    `status` = NULL,
    `startdatetime` = NULL,
    `completiondatetime` = NULL,
    `progress` = NULL,
    `batchevents` = NULL,
    initialize = function(`id`=NULL, `status`=NULL, `startdatetime`=NULL, `completiondatetime`=NULL, `progress`=NULL, `batchevents`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`startdatetime`)) {
        stopifnot(is.character(`startdatetime`), length(`startdatetime`) == 1)
        self$`startdatetime` <- `startdatetime`
      }
      if (!is.null(`completiondatetime`)) {
        stopifnot(is.character(`completiondatetime`), length(`completiondatetime`) == 1)
        self$`completiondatetime` <- `completiondatetime`
      }
      if (!is.null(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        self$`progress` <- `progress`
      }
      if (!is.null(`batchevents`)) {
        stopifnot(is.vector(`batchevents`), length(`batchevents`) != 0)
        sapply(`batchevents`, function(x) stopifnot(R6::is.R6(x)))
        self$`batchevents` <- `batchevents`
      }
    },
    toJSON = function() {
      FIABCalculationStatusObject <- list()
      if (!is.null(self$`id`)) {
        FIABCalculationStatusObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`status`)) {
        FIABCalculationStatusObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`startdatetime`)) {
        FIABCalculationStatusObject[['startdatetime']] <-
          self$`startdatetime`
      }
      if (!is.null(self$`completiondatetime`)) {
        FIABCalculationStatusObject[['completiondatetime']] <-
          self$`completiondatetime`
      }
      if (!is.null(self$`progress`)) {
        FIABCalculationStatusObject[['progress']] <-
          self$`progress`
      }
      if (!is.null(self$`batchevents`)) {
        FIABCalculationStatusObject[['batchevents']] <-
          lapply(self$`batchevents`, function(x) x$toJSON())
      }

      FIABCalculationStatusObject
    },
    fromJSON = function(FIABCalculationStatusJson) {
      FIABCalculationStatusObject <- jsonlite::fromJSON(FIABCalculationStatusJson)
      if (!is.null(FIABCalculationStatusObject$`id`)) {
        self$`id` <- FIABCalculationStatusObject$`id`
      }
      if (!is.null(FIABCalculationStatusObject$`status`)) {
        self$`status` <- FIABCalculationStatusObject$`status`
      }
      if (!is.null(FIABCalculationStatusObject$`startdatetime`)) {
        self$`startdatetime` <- FIABCalculationStatusObject$`startdatetime`
      }
      if (!is.null(FIABCalculationStatusObject$`completiondatetime`)) {
        self$`completiondatetime` <- FIABCalculationStatusObject$`completiondatetime`
      }
      if (!is.null(FIABCalculationStatusObject$`progress`)) {
        self$`progress` <- FIABCalculationStatusObject$`progress`
      }
      if (!is.null(FIABCalculationStatusObject$`batchevents`)) {
        self$`batchevents` <- ApiClient$new()$deserializeObj(FIABCalculationStatusObject$`batchevents`, "array[EventSummary]", loadNamespace("factset.analyticsapi.engines"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`startdatetime`)) {
        sprintf(
        '"startdatetime":
          "%s"
                ',
        self$`startdatetime`
        )},
        if (!is.null(self$`completiondatetime`)) {
        sprintf(
        '"completiondatetime":
          "%s"
                ',
        self$`completiondatetime`
        )},
        if (!is.null(self$`progress`)) {
        sprintf(
        '"progress":
          %d
                ',
        self$`progress`
        )},
        if (!is.null(self$`batchevents`)) {
        sprintf(
        '"batchevents":
        [%s]
',
        paste(sapply(self$`batchevents`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FIABCalculationStatusJson) {
      FIABCalculationStatusObject <- jsonlite::fromJSON(FIABCalculationStatusJson)
      self$`id` <- FIABCalculationStatusObject$`id`
      self$`status` <- FIABCalculationStatusObject$`status`
      self$`startdatetime` <- FIABCalculationStatusObject$`startdatetime`
      self$`completiondatetime` <- FIABCalculationStatusObject$`completiondatetime`
      self$`progress` <- FIABCalculationStatusObject$`progress`
      self$`batchevents` <- ApiClient$new()$deserializeObj(FIABCalculationStatusObject$`batchevents`, "array[EventSummary]", loadNamespace("factset.analyticsapi.engines"))
      self
    }
  )
)
