# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FPOAccount
#' @description FPOAccount Class
#' @format An \code{R6Class} generator object
#' @field paDocument  \link{PaDoc} 
#'
#' @field id  character [optional]
#'
#' @field overrides  \link{OptimizerAccountOverrides} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FPOAccount <- R6::R6Class(
  'FPOAccount',
  public = list(
    `paDocument` = NULL,
    `id` = NULL,
    `overrides` = NULL,
    initialize = function(`paDocument`, `id`=NULL, `overrides`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`paDocument`)) {
        stopifnot(R6::is.R6(`paDocument`))
        self$`paDocument` <- `paDocument`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`overrides`)) {
        stopifnot(R6::is.R6(`overrides`))
        self$`overrides` <- `overrides`
      }
    },
    toJSON = function() {
      FPOAccountObject <- list()
      if (!is.null(self$`paDocument`)) {
        FPOAccountObject[['paDocument']] <-
          self$`paDocument`$toJSON()
      }
      if (!is.null(self$`id`)) {
        FPOAccountObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`overrides`)) {
        FPOAccountObject[['overrides']] <-
          self$`overrides`$toJSON()
      }

      FPOAccountObject
    },
    fromJSON = function(FPOAccountJson) {
      FPOAccountObject <- jsonlite::fromJSON(FPOAccountJson)
      if (!is.null(FPOAccountObject$`paDocument`)) {
        paDocumentObject <- PaDoc$new()
        paDocumentObject$fromJSON(jsonlite::toJSON(FPOAccountObject$paDocument, auto_unbox = TRUE, digits = NA))
        self$`paDocument` <- paDocumentObject
      }
      if (!is.null(FPOAccountObject$`id`)) {
        self$`id` <- FPOAccountObject$`id`
      }
      if (!is.null(FPOAccountObject$`overrides`)) {
        overridesObject <- OptimizerAccountOverrides$new()
        overridesObject$fromJSON(jsonlite::toJSON(FPOAccountObject$overrides, auto_unbox = TRUE, digits = NA))
        self$`overrides` <- overridesObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`paDocument`)) {
        sprintf(
        '"paDocument":
        %s
        ',
        jsonlite::toJSON(self$`paDocument`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`overrides`)) {
        sprintf(
        '"overrides":
        %s
        ',
        jsonlite::toJSON(self$`overrides`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FPOAccountJson) {
      FPOAccountObject <- jsonlite::fromJSON(FPOAccountJson)
      self$`paDocument` <- PaDoc$new()$fromJSON(jsonlite::toJSON(FPOAccountObject$paDocument, auto_unbox = TRUE, digits = NA))
      self$`id` <- FPOAccountObject$`id`
      self$`overrides` <- OptimizerAccountOverrides$new()$fromJSON(jsonlite::toJSON(FPOAccountObject$overrides, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
