# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title JobSettings
#' @description JobSettings Class
#' @format An \code{R6Class} generator object
#' @field yieldCurveDate  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobSettings <- R6::R6Class(
  'JobSettings',
  public = list(
    `yieldCurveDate` = NULL,
    initialize = function(`yieldCurveDate`, ...){
      local.optional.var <- list(...)
      if (!missing(`yieldCurveDate`)) {
        stopifnot(is.character(`yieldCurveDate`), length(`yieldCurveDate`) == 1)
        self$`yieldCurveDate` <- `yieldCurveDate`
      }
    },
    toJSON = function() {
      JobSettingsObject <- list()
      if (!is.null(self$`yieldCurveDate`)) {
        JobSettingsObject[['yieldCurveDate']] <-
          self$`yieldCurveDate`
      }

      JobSettingsObject
    },
    fromJSON = function(JobSettingsJson) {
      JobSettingsObject <- jsonlite::fromJSON(JobSettingsJson)
      if (!is.null(JobSettingsObject$`yieldCurveDate`)) {
        self$`yieldCurveDate` <- JobSettingsObject$`yieldCurveDate`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`yieldCurveDate`)) {
        sprintf(
        '"yieldCurveDate":
          "%s"
                ',
        self$`yieldCurveDate`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(JobSettingsJson) {
      JobSettingsObject <- jsonlite::fromJSON(JobSettingsJson)
      self$`yieldCurveDate` <- JobSettingsObject$`yieldCurveDate`
      self
    }
  )
)
