# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptimalHoldings
#' @description OptimalHoldings Class
#' @format An \code{R6Class} generator object
#' @field identifiertype  character [optional]
#'
#' @field includecash  character [optional]
#'
#' @field excludezero  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptimalHoldings <- R6::R6Class(
  'OptimalHoldings',
  public = list(
    `identifiertype` = NULL,
    `includecash` = NULL,
    `excludezero` = NULL,
    initialize = function(`identifiertype`=NULL, `includecash`=NULL, `excludezero`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`identifiertype`)) {
        stopifnot(is.character(`identifiertype`), length(`identifiertype`) == 1)
        self$`identifiertype` <- `identifiertype`
      }
      if (!is.null(`includecash`)) {
        self$`includecash` <- `includecash`
      }
      if (!is.null(`excludezero`)) {
        self$`excludezero` <- `excludezero`
      }
    },
    toJSON = function() {
      OptimalHoldingsObject <- list()
      if (!is.null(self$`identifiertype`)) {
        OptimalHoldingsObject[['identifiertype']] <-
          self$`identifiertype`
      }
      if (!is.null(self$`includecash`)) {
        OptimalHoldingsObject[['includecash']] <-
          self$`includecash`
      }
      if (!is.null(self$`excludezero`)) {
        OptimalHoldingsObject[['excludezero']] <-
          self$`excludezero`
      }

      OptimalHoldingsObject
    },
    fromJSON = function(OptimalHoldingsJson) {
      OptimalHoldingsObject <- jsonlite::fromJSON(OptimalHoldingsJson)
      if (!is.null(OptimalHoldingsObject$`identifiertype`)) {
        self$`identifiertype` <- OptimalHoldingsObject$`identifiertype`
      }
      if (!is.null(OptimalHoldingsObject$`includecash`)) {
        self$`includecash` <- OptimalHoldingsObject$`includecash`
      }
      if (!is.null(OptimalHoldingsObject$`excludezero`)) {
        self$`excludezero` <- OptimalHoldingsObject$`excludezero`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`identifiertype`)) {
        sprintf(
        '"identifiertype":
          "%s"
                ',
        self$`identifiertype`
        )},
        if (!is.null(self$`includecash`)) {
        sprintf(
        '"includecash":
          "%s"
                ',
        self$`includecash`
        )},
        if (!is.null(self$`excludezero`)) {
        sprintf(
        '"excludezero":
          "%s"
                ',
        self$`excludezero`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimalHoldingsJson) {
      OptimalHoldingsObject <- jsonlite::fromJSON(OptimalHoldingsJson)
      self$`identifiertype` <- OptimalHoldingsObject$`identifiertype`
      self$`includecash` <- OptimalHoldingsObject$`includecash`
      self$`excludezero` <- OptimalHoldingsObject$`excludezero`
      self
    }
  )
)
