# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptimizerAccountOverrides
#' @description OptimizerAccountOverrides Class
#' @format An \code{R6Class} generator object
#' @field portfolio  character [optional]
#'
#' @field benchmark  character [optional]
#'
#' @field riskmodelid  character [optional]
#'
#' @field currency  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptimizerAccountOverrides <- R6::R6Class(
  'OptimizerAccountOverrides',
  public = list(
    `portfolio` = NULL,
    `benchmark` = NULL,
    `riskmodelid` = NULL,
    `currency` = NULL,
    initialize = function(`portfolio`=NULL, `benchmark`=NULL, `riskmodelid`=NULL, `currency`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`portfolio`)) {
        stopifnot(is.character(`portfolio`), length(`portfolio`) == 1)
        self$`portfolio` <- `portfolio`
      }
      if (!is.null(`benchmark`)) {
        stopifnot(is.character(`benchmark`), length(`benchmark`) == 1)
        self$`benchmark` <- `benchmark`
      }
      if (!is.null(`riskmodelid`)) {
        stopifnot(is.character(`riskmodelid`), length(`riskmodelid`) == 1)
        self$`riskmodelid` <- `riskmodelid`
      }
      if (!is.null(`currency`)) {
        stopifnot(is.character(`currency`), length(`currency`) == 1)
        self$`currency` <- `currency`
      }
    },
    toJSON = function() {
      OptimizerAccountOverridesObject <- list()
      if (!is.null(self$`portfolio`)) {
        OptimizerAccountOverridesObject[['portfolio']] <-
          self$`portfolio`
      }
      if (!is.null(self$`benchmark`)) {
        OptimizerAccountOverridesObject[['benchmark']] <-
          self$`benchmark`
      }
      if (!is.null(self$`riskmodelid`)) {
        OptimizerAccountOverridesObject[['riskmodelid']] <-
          self$`riskmodelid`
      }
      if (!is.null(self$`currency`)) {
        OptimizerAccountOverridesObject[['currency']] <-
          self$`currency`
      }

      OptimizerAccountOverridesObject
    },
    fromJSON = function(OptimizerAccountOverridesJson) {
      OptimizerAccountOverridesObject <- jsonlite::fromJSON(OptimizerAccountOverridesJson)
      if (!is.null(OptimizerAccountOverridesObject$`portfolio`)) {
        self$`portfolio` <- OptimizerAccountOverridesObject$`portfolio`
      }
      if (!is.null(OptimizerAccountOverridesObject$`benchmark`)) {
        self$`benchmark` <- OptimizerAccountOverridesObject$`benchmark`
      }
      if (!is.null(OptimizerAccountOverridesObject$`riskmodelid`)) {
        self$`riskmodelid` <- OptimizerAccountOverridesObject$`riskmodelid`
      }
      if (!is.null(OptimizerAccountOverridesObject$`currency`)) {
        self$`currency` <- OptimizerAccountOverridesObject$`currency`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`portfolio`)) {
        sprintf(
        '"portfolio":
          "%s"
                ',
        self$`portfolio`
        )},
        if (!is.null(self$`benchmark`)) {
        sprintf(
        '"benchmark":
          "%s"
                ',
        self$`benchmark`
        )},
        if (!is.null(self$`riskmodelid`)) {
        sprintf(
        '"riskmodelid":
          "%s"
                ',
        self$`riskmodelid`
        )},
        if (!is.null(self$`currency`)) {
        sprintf(
        '"currency":
          "%s"
                ',
        self$`currency`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimizerAccountOverridesJson) {
      OptimizerAccountOverridesObject <- jsonlite::fromJSON(OptimizerAccountOverridesJson)
      self$`portfolio` <- OptimizerAccountOverridesObject$`portfolio`
      self$`benchmark` <- OptimizerAccountOverridesObject$`benchmark`
      self$`riskmodelid` <- OptimizerAccountOverridesObject$`riskmodelid`
      self$`currency` <- OptimizerAccountOverridesObject$`currency`
      self
    }
  )
)
