# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptimizerOptimalHoldings
#' @description OptimizerOptimalHoldings Class
#' @format An \code{R6Class} generator object
#' @field identifierType  character [optional]
#'
#' @field includeCash  character [optional]
#'
#' @field excludeZero  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptimizerOptimalHoldings <- R6::R6Class(
  'OptimizerOptimalHoldings',
  public = list(
    `identifierType` = NULL,
    `includeCash` = NULL,
    `excludeZero` = NULL,
    initialize = function(`identifierType`=NULL, `includeCash`=NULL, `excludeZero`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`identifierType`)) {
        stopifnot(is.character(`identifierType`), length(`identifierType`) == 1)
        self$`identifierType` <- `identifierType`
      }
      if (!is.null(`includeCash`)) {
        self$`includeCash` <- `includeCash`
      }
      if (!is.null(`excludeZero`)) {
        self$`excludeZero` <- `excludeZero`
      }
    },
    toJSON = function() {
      OptimizerOptimalHoldingsObject <- list()
      if (!is.null(self$`identifierType`)) {
        OptimizerOptimalHoldingsObject[['identifierType']] <-
          self$`identifierType`
      }
      if (!is.null(self$`includeCash`)) {
        OptimizerOptimalHoldingsObject[['includeCash']] <-
          self$`includeCash`
      }
      if (!is.null(self$`excludeZero`)) {
        OptimizerOptimalHoldingsObject[['excludeZero']] <-
          self$`excludeZero`
      }

      OptimizerOptimalHoldingsObject
    },
    fromJSON = function(OptimizerOptimalHoldingsJson) {
      OptimizerOptimalHoldingsObject <- jsonlite::fromJSON(OptimizerOptimalHoldingsJson)
      if (!is.null(OptimizerOptimalHoldingsObject$`identifierType`)) {
        self$`identifierType` <- OptimizerOptimalHoldingsObject$`identifierType`
      }
      if (!is.null(OptimizerOptimalHoldingsObject$`includeCash`)) {
        self$`includeCash` <- OptimizerOptimalHoldingsObject$`includeCash`
      }
      if (!is.null(OptimizerOptimalHoldingsObject$`excludeZero`)) {
        self$`excludeZero` <- OptimizerOptimalHoldingsObject$`excludeZero`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`identifierType`)) {
        sprintf(
        '"identifierType":
          "%s"
                ',
        self$`identifierType`
        )},
        if (!is.null(self$`includeCash`)) {
        sprintf(
        '"includeCash":
          "%s"
                ',
        self$`includeCash`
        )},
        if (!is.null(self$`excludeZero`)) {
        sprintf(
        '"excludeZero":
          "%s"
                ',
        self$`excludeZero`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimizerOptimalHoldingsJson) {
      OptimizerOptimalHoldingsObject <- jsonlite::fromJSON(OptimizerOptimalHoldingsJson)
      self$`identifierType` <- OptimizerOptimalHoldingsObject$`identifierType`
      self$`includeCash` <- OptimizerOptimalHoldingsObject$`includeCash`
      self$`excludeZero` <- OptimizerOptimalHoldingsObject$`excludeZero`
      self
    }
  )
)
