# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptimizerOutputTypes
#' @description OptimizerOutputTypes Class
#' @format An \code{R6Class} generator object
#' @field trades  \link{OptimizerTradesList} [optional]
#'
#' @field optimal  \link{OptimizerOptimalHoldings} [optional]
#'
#' @field account  \link{OptimalPortfolio} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptimizerOutputTypes <- R6::R6Class(
  'OptimizerOutputTypes',
  public = list(
    `trades` = NULL,
    `optimal` = NULL,
    `account` = NULL,
    initialize = function(`trades`=NULL, `optimal`=NULL, `account`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`trades`)) {
        stopifnot(R6::is.R6(`trades`))
        self$`trades` <- `trades`
      }
      if (!is.null(`optimal`)) {
        stopifnot(R6::is.R6(`optimal`))
        self$`optimal` <- `optimal`
      }
      if (!is.null(`account`)) {
        stopifnot(R6::is.R6(`account`))
        self$`account` <- `account`
      }
    },
    toJSON = function() {
      OptimizerOutputTypesObject <- list()
      if (!is.null(self$`trades`)) {
        OptimizerOutputTypesObject[['trades']] <-
          self$`trades`$toJSON()
      }
      if (!is.null(self$`optimal`)) {
        OptimizerOutputTypesObject[['optimal']] <-
          self$`optimal`$toJSON()
      }
      if (!is.null(self$`account`)) {
        OptimizerOutputTypesObject[['account']] <-
          self$`account`$toJSON()
      }

      OptimizerOutputTypesObject
    },
    fromJSON = function(OptimizerOutputTypesJson) {
      OptimizerOutputTypesObject <- jsonlite::fromJSON(OptimizerOutputTypesJson)
      if (!is.null(OptimizerOutputTypesObject$`trades`)) {
        tradesObject <- OptimizerTradesList$new()
        tradesObject$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$trades, auto_unbox = TRUE, digits = NA))
        self$`trades` <- tradesObject
      }
      if (!is.null(OptimizerOutputTypesObject$`optimal`)) {
        optimalObject <- OptimizerOptimalHoldings$new()
        optimalObject$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$optimal, auto_unbox = TRUE, digits = NA))
        self$`optimal` <- optimalObject
      }
      if (!is.null(OptimizerOutputTypesObject$`account`)) {
        accountObject <- OptimalPortfolio$new()
        accountObject$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$account, auto_unbox = TRUE, digits = NA))
        self$`account` <- accountObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`trades`)) {
        sprintf(
        '"trades":
        %s
        ',
        jsonlite::toJSON(self$`trades`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`optimal`)) {
        sprintf(
        '"optimal":
        %s
        ',
        jsonlite::toJSON(self$`optimal`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
        %s
        ',
        jsonlite::toJSON(self$`account`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimizerOutputTypesJson) {
      OptimizerOutputTypesObject <- jsonlite::fromJSON(OptimizerOutputTypesJson)
      self$`trades` <- OptimizerTradesList$new()$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$trades, auto_unbox = TRUE, digits = NA))
      self$`optimal` <- OptimizerOptimalHoldings$new()$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$optimal, auto_unbox = TRUE, digits = NA))
      self$`account` <- OptimalPortfolio$new()$fromJSON(jsonlite::toJSON(OptimizerOutputTypesObject$account, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
