# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptimalPortfolio
#' @description OptimalPortfolio Class
#' @format An \code{R6Class} generator object
#' @field acctname  character [optional]
#'
#' @field excludezero  character [optional]
#'
#' @field archivedate  character [optional]
#'
#' @field ifexists  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptimalPortfolio <- R6::R6Class(
  'OptimalPortfolio',
  public = list(
    `acctname` = NULL,
    `excludezero` = NULL,
    `archivedate` = NULL,
    `ifexists` = NULL,
    initialize = function(`acctname`=NULL, `excludezero`=NULL, `archivedate`=NULL, `ifexists`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`acctname`)) {
        stopifnot(is.character(`acctname`), length(`acctname`) == 1)
        self$`acctname` <- `acctname`
      }
      if (!is.null(`excludezero`)) {
        self$`excludezero` <- `excludezero`
      }
      if (!is.null(`archivedate`)) {
        stopifnot(is.character(`archivedate`), length(`archivedate`) == 1)
        self$`archivedate` <- `archivedate`
      }
      if (!is.null(`ifexists`)) {
        stopifnot(is.character(`ifexists`), length(`ifexists`) == 1)
        self$`ifexists` <- `ifexists`
      }
    },
    toJSON = function() {
      OptimalPortfolioObject <- list()
      if (!is.null(self$`acctname`)) {
        OptimalPortfolioObject[['acctname']] <-
          self$`acctname`
      }
      if (!is.null(self$`excludezero`)) {
        OptimalPortfolioObject[['excludezero']] <-
          self$`excludezero`
      }
      if (!is.null(self$`archivedate`)) {
        OptimalPortfolioObject[['archivedate']] <-
          self$`archivedate`
      }
      if (!is.null(self$`ifexists`)) {
        OptimalPortfolioObject[['ifexists']] <-
          self$`ifexists`
      }

      OptimalPortfolioObject
    },
    fromJSON = function(OptimalPortfolioJson) {
      OptimalPortfolioObject <- jsonlite::fromJSON(OptimalPortfolioJson)
      if (!is.null(OptimalPortfolioObject$`acctname`)) {
        self$`acctname` <- OptimalPortfolioObject$`acctname`
      }
      if (!is.null(OptimalPortfolioObject$`excludezero`)) {
        self$`excludezero` <- OptimalPortfolioObject$`excludezero`
      }
      if (!is.null(OptimalPortfolioObject$`archivedate`)) {
        self$`archivedate` <- OptimalPortfolioObject$`archivedate`
      }
      if (!is.null(OptimalPortfolioObject$`ifexists`)) {
        self$`ifexists` <- OptimalPortfolioObject$`ifexists`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`acctname`)) {
        sprintf(
        '"acctname":
          "%s"
                ',
        self$`acctname`
        )},
        if (!is.null(self$`excludezero`)) {
        sprintf(
        '"excludezero":
          "%s"
                ',
        self$`excludezero`
        )},
        if (!is.null(self$`archivedate`)) {
        sprintf(
        '"archivedate":
          "%s"
                ',
        self$`archivedate`
        )},
        if (!is.null(self$`ifexists`)) {
        sprintf(
        '"ifexists":
          "%s"
                ',
        self$`ifexists`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimalPortfolioJson) {
      OptimalPortfolioObject <- jsonlite::fromJSON(OptimalPortfolioJson)
      self$`acctname` <- OptimalPortfolioObject$`acctname`
      self$`excludezero` <- OptimalPortfolioObject$`excludezero`
      self$`archivedate` <- OptimalPortfolioObject$`archivedate`
      self$`ifexists` <- OptimalPortfolioObject$`ifexists`
      self
    }
  )
)
