# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Optimization
#' @description Optimization Class
#' @format An \code{R6Class} generator object
#' @field riskmodeldate  character [optional]
#'
#' @field backtestdate  character [optional]
#'
#' @field cashflow  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Optimization <- R6::R6Class(
  'Optimization',
  public = list(
    `riskmodeldate` = NULL,
    `backtestdate` = NULL,
    `cashflow` = NULL,
    initialize = function(`riskmodeldate`=NULL, `backtestdate`=NULL, `cashflow`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`riskmodeldate`)) {
        stopifnot(is.character(`riskmodeldate`), length(`riskmodeldate`) == 1)
        self$`riskmodeldate` <- `riskmodeldate`
      }
      if (!is.null(`backtestdate`)) {
        stopifnot(is.character(`backtestdate`), length(`backtestdate`) == 1)
        self$`backtestdate` <- `backtestdate`
      }
      if (!is.null(`cashflow`)) {
        stopifnot(is.character(`cashflow`), length(`cashflow`) == 1)
        self$`cashflow` <- `cashflow`
      }
    },
    toJSON = function() {
      OptimizationObject <- list()
      if (!is.null(self$`riskmodeldate`)) {
        OptimizationObject[['riskmodeldate']] <-
          self$`riskmodeldate`
      }
      if (!is.null(self$`backtestdate`)) {
        OptimizationObject[['backtestdate']] <-
          self$`backtestdate`
      }
      if (!is.null(self$`cashflow`)) {
        OptimizationObject[['cashflow']] <-
          self$`cashflow`
      }

      OptimizationObject
    },
    fromJSON = function(OptimizationJson) {
      OptimizationObject <- jsonlite::fromJSON(OptimizationJson)
      if (!is.null(OptimizationObject$`riskmodeldate`)) {
        self$`riskmodeldate` <- OptimizationObject$`riskmodeldate`
      }
      if (!is.null(OptimizationObject$`backtestdate`)) {
        self$`backtestdate` <- OptimizationObject$`backtestdate`
      }
      if (!is.null(OptimizationObject$`cashflow`)) {
        self$`cashflow` <- OptimizationObject$`cashflow`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`riskmodeldate`)) {
        sprintf(
        '"riskmodeldate":
          "%s"
                ',
        self$`riskmodeldate`
        )},
        if (!is.null(self$`backtestdate`)) {
        sprintf(
        '"backtestdate":
          "%s"
                ',
        self$`backtestdate`
        )},
        if (!is.null(self$`cashflow`)) {
        sprintf(
        '"cashflow":
          "%s"
                ',
        self$`cashflow`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimizationJson) {
      OptimizationObject <- jsonlite::fromJSON(OptimizationJson)
      self$`riskmodeldate` <- OptimizationObject$`riskmodeldate`
      self$`backtestdate` <- OptimizationObject$`backtestdate`
      self$`cashflow` <- OptimizationObject$`cashflow`
      self
    }
  )
)
