# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Optimization
#' @description Optimization Class
#' @format An \code{R6Class} generator object
#' @field riskModelDate  character [optional]
#'
#' @field backtestDate  character [optional]
#'
#' @field cashflow  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Optimization <- R6::R6Class(
  'Optimization',
  public = list(
    `riskModelDate` = NULL,
    `backtestDate` = NULL,
    `cashflow` = NULL,
    initialize = function(`riskModelDate`=NULL, `backtestDate`=NULL, `cashflow`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`riskModelDate`)) {
        stopifnot(is.character(`riskModelDate`), length(`riskModelDate`) == 1)
        self$`riskModelDate` <- `riskModelDate`
      }
      if (!is.null(`backtestDate`)) {
        stopifnot(is.character(`backtestDate`), length(`backtestDate`) == 1)
        self$`backtestDate` <- `backtestDate`
      }
      if (!is.null(`cashflow`)) {
        stopifnot(is.character(`cashflow`), length(`cashflow`) == 1)
        self$`cashflow` <- `cashflow`
      }
    },
    toJSON = function() {
      OptimizationObject <- list()
      if (!is.null(self$`riskModelDate`)) {
        OptimizationObject[['riskModelDate']] <-
          self$`riskModelDate`
      }
      if (!is.null(self$`backtestDate`)) {
        OptimizationObject[['backtestDate']] <-
          self$`backtestDate`
      }
      if (!is.null(self$`cashflow`)) {
        OptimizationObject[['cashflow']] <-
          self$`cashflow`
      }

      OptimizationObject
    },
    fromJSON = function(OptimizationJson) {
      OptimizationObject <- jsonlite::fromJSON(OptimizationJson)
      if (!is.null(OptimizationObject$`riskModelDate`)) {
        self$`riskModelDate` <- OptimizationObject$`riskModelDate`
      }
      if (!is.null(OptimizationObject$`backtestDate`)) {
        self$`backtestDate` <- OptimizationObject$`backtestDate`
      }
      if (!is.null(OptimizationObject$`cashflow`)) {
        self$`cashflow` <- OptimizationObject$`cashflow`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`riskModelDate`)) {
        sprintf(
        '"riskModelDate":
          "%s"
                ',
        self$`riskModelDate`
        )},
        if (!is.null(self$`backtestDate`)) {
        sprintf(
        '"backtestDate":
          "%s"
                ',
        self$`backtestDate`
        )},
        if (!is.null(self$`cashflow`)) {
        sprintf(
        '"cashflow":
          "%s"
                ',
        self$`cashflow`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptimizationJson) {
      OptimizationObject <- jsonlite::fromJSON(OptimizationJson)
      self$`riskModelDate` <- OptimizationObject$`riskModelDate`
      self$`backtestDate` <- OptimizationObject$`backtestDate`
      self$`cashflow` <- OptimizationObject$`cashflow`
      self
    }
  )
)
