# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OutputTypes
#' @description OutputTypes Class
#' @format An \code{R6Class} generator object
#' @field trades  \link{TradesList} [optional]
#'
#' @field optimal  \link{OptimalHoldings} [optional]
#'
#' @field account  \link{OptimalPortfolio} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OutputTypes <- R6::R6Class(
  'OutputTypes',
  public = list(
    `trades` = NULL,
    `optimal` = NULL,
    `account` = NULL,
    initialize = function(`trades`=NULL, `optimal`=NULL, `account`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`trades`)) {
        stopifnot(R6::is.R6(`trades`))
        self$`trades` <- `trades`
      }
      if (!is.null(`optimal`)) {
        stopifnot(R6::is.R6(`optimal`))
        self$`optimal` <- `optimal`
      }
      if (!is.null(`account`)) {
        stopifnot(R6::is.R6(`account`))
        self$`account` <- `account`
      }
    },
    toJSON = function() {
      OutputTypesObject <- list()
      if (!is.null(self$`trades`)) {
        OutputTypesObject[['trades']] <-
          self$`trades`$toJSON()
      }
      if (!is.null(self$`optimal`)) {
        OutputTypesObject[['optimal']] <-
          self$`optimal`$toJSON()
      }
      if (!is.null(self$`account`)) {
        OutputTypesObject[['account']] <-
          self$`account`$toJSON()
      }

      OutputTypesObject
    },
    fromJSON = function(OutputTypesJson) {
      OutputTypesObject <- jsonlite::fromJSON(OutputTypesJson)
      if (!is.null(OutputTypesObject$`trades`)) {
        tradesObject <- TradesList$new()
        tradesObject$fromJSON(jsonlite::toJSON(OutputTypesObject$trades, auto_unbox = TRUE, digits = NA))
        self$`trades` <- tradesObject
      }
      if (!is.null(OutputTypesObject$`optimal`)) {
        optimalObject <- OptimalHoldings$new()
        optimalObject$fromJSON(jsonlite::toJSON(OutputTypesObject$optimal, auto_unbox = TRUE, digits = NA))
        self$`optimal` <- optimalObject
      }
      if (!is.null(OutputTypesObject$`account`)) {
        accountObject <- OptimalPortfolio$new()
        accountObject$fromJSON(jsonlite::toJSON(OutputTypesObject$account, auto_unbox = TRUE, digits = NA))
        self$`account` <- accountObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`trades`)) {
        sprintf(
        '"trades":
        %s
        ',
        jsonlite::toJSON(self$`trades`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`optimal`)) {
        sprintf(
        '"optimal":
        %s
        ',
        jsonlite::toJSON(self$`optimal`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
        %s
        ',
        jsonlite::toJSON(self$`account`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OutputTypesJson) {
      OutputTypesObject <- jsonlite::fromJSON(OutputTypesJson)
      self$`trades` <- TradesList$new()$fromJSON(jsonlite::toJSON(OutputTypesObject$trades, auto_unbox = TRUE, digits = NA))
      self$`optimal` <- OptimalHoldings$new()$fromJSON(jsonlite::toJSON(OutputTypesObject$optimal, auto_unbox = TRUE, digits = NA))
      self$`account` <- OptimalPortfolio$new()$fromJSON(jsonlite::toJSON(OutputTypesObject$account, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
