# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PubCalculationParameters
#' @description PubCalculationParameters Class
#' @format An \code{R6Class} generator object
#' @field document  character 
#'
#' @field account  \link{PubIdentifier} 
#'
#' @field dates  \link{PubDateParameters} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PubCalculationParameters <- R6::R6Class(
  'PubCalculationParameters',
  public = list(
    `document` = NULL,
    `account` = NULL,
    `dates` = NULL,
    initialize = function(`document`, `account`, `dates`, ...){
      local.optional.var <- list(...)
      if (!missing(`document`)) {
        stopifnot(is.character(`document`), length(`document`) == 1)
        self$`document` <- `document`
      }
      if (!missing(`account`)) {
        stopifnot(R6::is.R6(`account`))
        self$`account` <- `account`
      }
      if (!missing(`dates`)) {
        stopifnot(R6::is.R6(`dates`))
        self$`dates` <- `dates`
      }
    },
    toJSON = function() {
      PubCalculationParametersObject <- list()
      if (!is.null(self$`document`)) {
        PubCalculationParametersObject[['document']] <-
          self$`document`
      }
      if (!is.null(self$`account`)) {
        PubCalculationParametersObject[['account']] <-
          self$`account`$toJSON()
      }
      if (!is.null(self$`dates`)) {
        PubCalculationParametersObject[['dates']] <-
          self$`dates`$toJSON()
      }

      PubCalculationParametersObject
    },
    fromJSON = function(PubCalculationParametersJson) {
      PubCalculationParametersObject <- jsonlite::fromJSON(PubCalculationParametersJson)
      if (!is.null(PubCalculationParametersObject$`document`)) {
        self$`document` <- PubCalculationParametersObject$`document`
      }
      if (!is.null(PubCalculationParametersObject$`account`)) {
        accountObject <- PubIdentifier$new()
        accountObject$fromJSON(jsonlite::toJSON(PubCalculationParametersObject$account, auto_unbox = TRUE, digits = NA))
        self$`account` <- accountObject
      }
      if (!is.null(PubCalculationParametersObject$`dates`)) {
        datesObject <- PubDateParameters$new()
        datesObject$fromJSON(jsonlite::toJSON(PubCalculationParametersObject$dates, auto_unbox = TRUE, digits = NA))
        self$`dates` <- datesObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`document`)) {
        sprintf(
        '"document":
          "%s"
                ',
        self$`document`
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
        %s
        ',
        jsonlite::toJSON(self$`account`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`dates`)) {
        sprintf(
        '"dates":
        %s
        ',
        jsonlite::toJSON(self$`dates`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PubCalculationParametersJson) {
      PubCalculationParametersObject <- jsonlite::fromJSON(PubCalculationParametersJson)
      self$`document` <- PubCalculationParametersObject$`document`
      self$`account` <- PubIdentifier$new()$fromJSON(jsonlite::toJSON(PubCalculationParametersObject$account, auto_unbox = TRUE, digits = NA))
      self$`dates` <- PubDateParameters$new()$fromJSON(jsonlite::toJSON(PubCalculationParametersObject$dates, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
