# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PubIdentifier
#' @description PubIdentifier Class
#' @format An \code{R6Class} generator object
#' @field id  character 
#'
#' @field holdingsmode  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PubIdentifier <- R6::R6Class(
  'PubIdentifier',
  public = list(
    `id` = NULL,
    `holdingsmode` = NULL,
    initialize = function(`id`, `holdingsmode`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`holdingsmode`)) {
        stopifnot(is.character(`holdingsmode`), length(`holdingsmode`) == 1)
        self$`holdingsmode` <- `holdingsmode`
      }
    },
    toJSON = function() {
      PubIdentifierObject <- list()
      if (!is.null(self$`id`)) {
        PubIdentifierObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`holdingsmode`)) {
        PubIdentifierObject[['holdingsmode']] <-
          self$`holdingsmode`
      }

      PubIdentifierObject
    },
    fromJSON = function(PubIdentifierJson) {
      PubIdentifierObject <- jsonlite::fromJSON(PubIdentifierJson)
      if (!is.null(PubIdentifierObject$`id`)) {
        self$`id` <- PubIdentifierObject$`id`
      }
      if (!is.null(PubIdentifierObject$`holdingsmode`)) {
        self$`holdingsmode` <- PubIdentifierObject$`holdingsmode`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`holdingsmode`)) {
        sprintf(
        '"holdingsmode":
          "%s"
                ',
        self$`holdingsmode`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PubIdentifierJson) {
      PubIdentifierObject <- jsonlite::fromJSON(PubIdentifierJson)
      self$`id` <- PubIdentifierObject$`id`
      self$`holdingsmode` <- PubIdentifierObject$`holdingsmode`
      self
    }
  )
)
