# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PubDateParameters
#' @description PubDateParameters Class
#' @format An \code{R6Class} generator object
#' @field startdate  character [optional]
#'
#' @field enddate  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PubDateParameters <- R6::R6Class(
  'PubDateParameters',
  public = list(
    `startdate` = NULL,
    `enddate` = NULL,
    initialize = function(`enddate`, `startdate`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`enddate`)) {
        stopifnot(is.character(`enddate`), length(`enddate`) == 1)
        self$`enddate` <- `enddate`
      }
      if (!is.null(`startdate`)) {
        stopifnot(is.character(`startdate`), length(`startdate`) == 1)
        self$`startdate` <- `startdate`
      }
    },
    toJSON = function() {
      PubDateParametersObject <- list()
      if (!is.null(self$`startdate`)) {
        PubDateParametersObject[['startdate']] <-
          self$`startdate`
      }
      if (!is.null(self$`enddate`)) {
        PubDateParametersObject[['enddate']] <-
          self$`enddate`
      }

      PubDateParametersObject
    },
    fromJSON = function(PubDateParametersJson) {
      PubDateParametersObject <- jsonlite::fromJSON(PubDateParametersJson)
      if (!is.null(PubDateParametersObject$`startdate`)) {
        self$`startdate` <- PubDateParametersObject$`startdate`
      }
      if (!is.null(PubDateParametersObject$`enddate`)) {
        self$`enddate` <- PubDateParametersObject$`enddate`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`startdate`)) {
        sprintf(
        '"startdate":
          "%s"
                ',
        self$`startdate`
        )},
        if (!is.null(self$`enddate`)) {
        sprintf(
        '"enddate":
          "%s"
                ',
        self$`enddate`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PubDateParametersJson) {
      PubDateParametersObject <- jsonlite::fromJSON(PubDateParametersJson)
      self$`startdate` <- PubDateParametersObject$`startdate`
      self$`enddate` <- PubDateParametersObject$`enddate`
      self
    }
  )
)
