# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Security
#' @description Security Class
#' @format An \code{R6Class} generator object
#' @field calcFromMethod  character 
#'
#' @field calcFromValue  numeric 
#'
#' @field face  numeric 
#'
#' @field symbol  character 
#'
#' @field settlementDate  character 
#'
#' @field discountCurve  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Security <- R6::R6Class(
  'Security',
  public = list(
    `calcFromMethod` = NULL,
    `calcFromValue` = NULL,
    `face` = NULL,
    `symbol` = NULL,
    `settlementDate` = NULL,
    `discountCurve` = NULL,
    initialize = function(`calcFromMethod`, `calcFromValue`, `face`, `symbol`, `settlementDate`, `discountCurve`, ...){
      local.optional.var <- list(...)
      if (!missing(`calcFromMethod`)) {
        stopifnot(is.character(`calcFromMethod`), length(`calcFromMethod`) == 1)
        self$`calcFromMethod` <- `calcFromMethod`
      }
      if (!missing(`calcFromValue`)) {
        stopifnot(is.numeric(`calcFromValue`), length(`calcFromValue`) == 1)
        self$`calcFromValue` <- `calcFromValue`
      }
      if (!missing(`face`)) {
        stopifnot(is.numeric(`face`), length(`face`) == 1)
        self$`face` <- `face`
      }
      if (!missing(`symbol`)) {
        stopifnot(is.character(`symbol`), length(`symbol`) == 1)
        self$`symbol` <- `symbol`
      }
      if (!missing(`settlementDate`)) {
        stopifnot(is.character(`settlementDate`), length(`settlementDate`) == 1)
        self$`settlementDate` <- `settlementDate`
      }
      if (!missing(`discountCurve`)) {
        stopifnot(is.character(`discountCurve`), length(`discountCurve`) == 1)
        self$`discountCurve` <- `discountCurve`
      }
    },
    toJSON = function() {
      SecurityObject <- list()
      if (!is.null(self$`calcFromMethod`)) {
        SecurityObject[['calcFromMethod']] <-
          self$`calcFromMethod`
      }
      if (!is.null(self$`calcFromValue`)) {
        SecurityObject[['calcFromValue']] <-
          self$`calcFromValue`
      }
      if (!is.null(self$`face`)) {
        SecurityObject[['face']] <-
          self$`face`
      }
      if (!is.null(self$`symbol`)) {
        SecurityObject[['symbol']] <-
          self$`symbol`
      }
      if (!is.null(self$`settlementDate`)) {
        SecurityObject[['settlementDate']] <-
          self$`settlementDate`
      }
      if (!is.null(self$`discountCurve`)) {
        SecurityObject[['discountCurve']] <-
          self$`discountCurve`
      }

      SecurityObject
    },
    fromJSON = function(SecurityJson) {
      SecurityObject <- jsonlite::fromJSON(SecurityJson)
      if (!is.null(SecurityObject$`calcFromMethod`)) {
        self$`calcFromMethod` <- SecurityObject$`calcFromMethod`
      }
      if (!is.null(SecurityObject$`calcFromValue`)) {
        self$`calcFromValue` <- SecurityObject$`calcFromValue`
      }
      if (!is.null(SecurityObject$`face`)) {
        self$`face` <- SecurityObject$`face`
      }
      if (!is.null(SecurityObject$`symbol`)) {
        self$`symbol` <- SecurityObject$`symbol`
      }
      if (!is.null(SecurityObject$`settlementDate`)) {
        self$`settlementDate` <- SecurityObject$`settlementDate`
      }
      if (!is.null(SecurityObject$`discountCurve`)) {
        self$`discountCurve` <- SecurityObject$`discountCurve`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`calcFromMethod`)) {
        sprintf(
        '"calcFromMethod":
          "%s"
                ',
        self$`calcFromMethod`
        )},
        if (!is.null(self$`calcFromValue`)) {
        sprintf(
        '"calcFromValue":
          %d
                ',
        self$`calcFromValue`
        )},
        if (!is.null(self$`face`)) {
        sprintf(
        '"face":
          %d
                ',
        self$`face`
        )},
        if (!is.null(self$`symbol`)) {
        sprintf(
        '"symbol":
          "%s"
                ',
        self$`symbol`
        )},
        if (!is.null(self$`settlementDate`)) {
        sprintf(
        '"settlementDate":
          "%s"
                ',
        self$`settlementDate`
        )},
        if (!is.null(self$`discountCurve`)) {
        sprintf(
        '"discountCurve":
          "%s"
                ',
        self$`discountCurve`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SecurityJson) {
      SecurityObject <- jsonlite::fromJSON(SecurityJson)
      self$`calcFromMethod` <- SecurityObject$`calcFromMethod`
      self$`calcFromValue` <- SecurityObject$`calcFromValue`
      self$`face` <- SecurityObject$`face`
      self$`symbol` <- SecurityObject$`symbol`
      self$`settlementDate` <- SecurityObject$`settlementDate`
      self$`discountCurve` <- SecurityObject$`discountCurve`
      self
    }
  )
)
