# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SPARCalculations operations
#' @description factset.analyticsapi.engines.SPARCalculations
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CancelCalculationById } \emph{ Cancel SPAR calculation }
#' This is the endpoint to cancel a previously submitted calculation.
#'
#' \itemize{
#' \item \emph{ @param } id character
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 204 | Expected response, calculation was canceled successfully.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid identifier provided.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | There was no request for the calculation identifier provided, or the request was already canceled for the provided identifier.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' \strong{ GetCalculationParameters } \emph{ Get SPAR calculation parameters by id }
#' This is the endpoint that returns the calculation parameters passed for a calculation.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{SPARCalculationParametersRoot} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Expected response, returns the SPAR calculation parameters.
#'
#' \item return type : SPARCalculationParametersRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' Content-Encoding \tab Standard HTTP header. Header value based on Accept-Encoding Request header. \cr
#' Content-Type \tab Standard HTTP header. \cr
#' Transfer-Encoding \tab Standard HTTP header. Header value will be set to Chunked if Accept-Encoding header is specified. \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid identifier provided.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | Calculation id not found
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' \strong{ GetCalculationStatusById } \emph{ Get SPAR calculation status by id }
#' This is the endpoint to check on the progress of a previously requested calculation.  If the calculation has finished computing, the location header will point to the result url.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{CalculationStatusRoot} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Expected response once calculation is completed.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' Content-Encoding \tab Standard HTTP header. Header value based on Accept-Encoding Request header. \cr
#' Content-Type \tab Standard HTTP header. \cr
#' Transfer-Encoding \tab Standard HTTP header. Header value will be set to Chunked if Accept-Encoding header is specified. \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 202 | Expected response returned if the calculation is not yet completed.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-FactSet-Api-PickUp-Progress \tab FactSet&#39;s progress header. \cr
#' Cache-Control \tab Standard HTTP header. Header will specify max-age in seconds. Polling can be adjusted based on the max-age value. \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid identifier provided.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | Calculation was already returned, provided id was not a requested calculation, or the calculation was cancelled
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' \strong{ GetCalculationUnitResultById } \emph{ Get SPAR calculation result by id }
#' This is the endpoint to get the result of a previously requested calculation.  If the calculation has finished computing, the body of the response will contain the requested document in JSON.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } unit.id character
#' \item \emph{ @param } accept character
#' \item \emph{ @returnType } \link{ObjectRoot} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Expected response once calculation is completed, returns JSON in the format specified in the Calculation parameters.
#'
#' \item return type : ObjectRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' Content-Encoding \tab Standard HTTP header. Header value based on Accept-Encoding Request header. \cr
#' Content-Type \tab Standard HTTP header. \cr
#' Transfer-Encoding \tab Standard HTTP header. Header value will be set to Chunked if Accept-Encoding header is specified. \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid identifier provided.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | Calculation was already returned, provided id was not a requested calculation, or the calculation was cancelled
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' \strong{ PostAndCalculate } \emph{ Create and Run SPAR calculation }
#' This endpoint runs the SPAR calculation specified in the POST body parameters.  It can take one or more units as input.    Remarks:    * Any settings in POST body will act as a one-time override over the settings saved in the SPAR template.
#'
#' \itemize{
#' \item \emph{ @param } x.fact.set.api.long.running.deadline integer
#' \item \emph{ @param } cache.control character
#' \item \emph{ @param } spar.calculation.parameters.root \link{SPARCalculationParametersRoot}
#' \item \emph{ @returnType } \link{CalculationStatusRoot} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 202 | Expected response, contains the poll URL in the Location header.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' Location \tab URL to poll for the resulting calculation \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 200 | Expected response, if the calculation has one unit and is completed with an error.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 201 | Expected response if the calculation has one unit and is completed in a short span, returns JSON in the format specified in the Calculation parameters.
#'
#' \item return type : ObjectRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid calculation parameters.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | One or more calculation settings were unavailable.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 415 | Missing/Invalid Content-Type header. Header needs to be set to application/json.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 429 | Rate limit reached. Cancel older requests using Cancel Calculation endpoint or wait for older requests to finish/expire.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' Retry-After \tab Time to wait in seconds before making a new request as the rate limit has reached. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' \strong{ PutAndCalculate } \emph{ Create or Update SPAR calculation and run it. }
#' This endpoint updates and run the SPAR calculation specified in the PUT body parameters. This also allows creating new SPAR calculations with custom ids.  It can take one or more units as input.    Remarks:    * Any settings in PUT body will act as a one-time override over the settings saved in the SPAR template.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } x.fact.set.api.long.running.deadline integer
#' \item \emph{ @param } cache.control character
#' \item \emph{ @param } spar.calculation.parameters.root \link{SPARCalculationParametersRoot}
#' \item \emph{ @returnType } \link{CalculationStatusRoot} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 202 | Expected response, contains the poll URL in the Location header.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' Location \tab URL to poll for the resulting calculation \cr
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 200 | Expected response, if the calculation has one unit and is completed with an error.
#'
#' \item return type : CalculationStatusRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 201 | Expected response if the calculation has one unit and is completed in a short span, returns JSON in the format specified in the Calculation parameters.
#'
#' \item return type : ObjectRoot 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 400 | Invalid Calculation Parameters.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 404 | One or more calculation settings were unavailable.
#'
#' \item return type : ClientErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 401 | Missing or invalid authentication.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 403 | User is forbidden with current credentials
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 415 | Missing/Invalid Content-Type header. Header needs to be set to application/json.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' }
#' \item status code : 429 | Rate limit reached. Cancel older requests using Cancel Calculation endpoint or wait for older requests to finish/expire.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' X-FactSet-Api-RateLimit-Limit \tab Number of allowed requests for the time window. \cr
#' X-FactSet-Api-RateLimit-Remaining \tab Number of requests left for the time window. \cr
#' X-FactSet-Api-RateLimit-Reset \tab Number of seconds remaining till rate limit resets. \cr
#' Retry-After \tab Time to wait in seconds before making a new request as the rate limit has reached. \cr
#' }
#' \item status code : 500 | Server error. Log the X-DataDirect-Request-Key header to assist in troubleshooting.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' \item status code : 503 | Request timed out. Retry the request in sometime.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' X-DataDirect-Request-Key \tab FactSet&#39;s request key header. \cr
#' X-FactSet-Api-Request-Key \tab Key to uniquely identify an Analytics API request. Only available after successful authentication. \cr
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CancelCalculationById  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.id <- 'id_example' # character | from url, provided from the location header in the Create and Run SPAR calculation endpoint
#'
#' #Cancel SPAR calculation
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$CancelCalculationById(var.id),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' ####################  GetCalculationParameters  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.id <- 'id_example' # character | from url, provided from the location header in the Create and Run SPAR calculation endpoint
#'
#' #Get SPAR calculation parameters by id
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$GetCalculationParameters(var.id),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # deserialized response object
#' response.object <- result$content
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' ####################  GetCalculationStatusById  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.id <- 'id_example' # character | from url, provided from the location header in the Create and Run SPAR calculation endpoint
#'
#' #Get SPAR calculation status by id
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$GetCalculationStatusById(var.id),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # deserialized response object
#' response.object <- result$content
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' ####################  GetCalculationUnitResultById  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.id <- 'id_example' # character | from url, provided from the location header in the Get SPAR calculation status by id endpoint
#' var.unit.id <- 'unit.id_example' # character | from url, provided from the location header in the Get SPAR calculation status by id endpoint
#' var.accept <- 'accept_example' # character | Standard HTTP header. Value can be gzip, compress, deflate, br, identity and/or *
#'
#' #Get SPAR calculation result by id
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$GetCalculationUnitResultById(var.id, var.unit.id, accept=var.accept),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # deserialized response object
#' response.object <- result$content
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' ####################  PostAndCalculate  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.x.fact.set.api.long.running.deadline <- 56 # integer | Long running deadline in seconds when only one unit is passed in the POST body.
#' var.cache.control <- 'cache.control_example' # character | Standard HTTP header.  Accepts no-cache, no-store, max-age, max-stale.
#' var.spar.calculation.parameters.root <- SPARCalculationParametersRoot$new() # SPARCalculationParametersRoot | Calculation Parameters
#'
#' #Create and Run SPAR calculation
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$PostAndCalculate(x.fact.set.api.long.running.deadline=var.x.fact.set.api.long.running.deadline, cache.control=var.cache.control, spar.calculation.parameters.root=var.spar.calculation.parameters.root),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # deserialized response object
#' response.object <- result$content
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' ####################  PutAndCalculate  ####################
#'
#' library(factset.analyticsapi.engines)
#' var.id <- 'id_example' # character | from url, provided from the location header in the Create and Run SPAR calculation endpoint
#' var.x.fact.set.api.long.running.deadline <- 56 # integer | Long running deadline in seconds when only one unit is passed in the PUT body.
#' var.cache.control <- 'cache.control_example' # character | Standard HTTP header.  Accepts no-cache, no-store, max-age, max-stale.
#' var.spar.calculation.parameters.root <- SPARCalculationParametersRoot$new() # SPARCalculationParametersRoot | Calculation Parameters
#'
#' #Create or Update SPAR calculation and run it.
#' api.instance <- SPARCalculationsApi$new()
#'
#' #Configure HTTP basic authorization: Basic
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#'result <- tryCatch(
#'             api.instance$PutAndCalculate(var.id, x.fact.set.api.long.running.deadline=var.x.fact.set.api.long.running.deadline, cache.control=var.cache.control, spar.calculation.parameters.root=var.spar.calculation.parameters.root),
#'             ApiException = function(ex) ex 
#'          )
#' # In case of error, print the error object 
#' if(!is.null(result$ApiException)) {
#'   cat(result$ApiException$toString())
#' } else {
#' # deserialized response object
#' response.object <- result$content
#' # response headers
#' response.headers <- result$response$headers
#' # response status code
#' response.status.code <- result$response$status_code
#' }
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
SPARCalculationsApi <- R6::R6Class(
  'SPARCalculationsApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CancelCalculationById = function(id, ...){
      apiResponse <- self$CancelCalculationByIdWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CancelCalculationByIdWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        rlang::abort(message = "Missing required parameter `id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `id`."))
      }

      urlPath <- "/analytics/engines/spar/v3/calculations/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    },
    GetCalculationParameters = function(id, ...){
      apiResponse <- self$GetCalculationParametersWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetCalculationParametersWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        rlang::abort(message = "Missing required parameter `id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `id`."))
      }

      urlPath <- "/analytics/engines/spar/v3/calculations/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "SPARCalculationParametersRoot", loadNamespace("factset.analyticsapi.engines")),
          error = function(e){
             rlang::abort(message = "Failed to deserialize response", .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    },
    GetCalculationStatusById = function(id, ...){
      apiResponse <- self$GetCalculationStatusByIdWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetCalculationStatusByIdWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        rlang::abort(message = "Missing required parameter `id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `id`."))
      }

      urlPath <- "/analytics/engines/spar/v3/calculations/{id}/status"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "CalculationStatusRoot", loadNamespace("factset.analyticsapi.engines")),
          error = function(e){
             rlang::abort(message = "Failed to deserialize response", .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    },
    GetCalculationUnitResultById = function(id, unit.id, accept=NULL, ...){
      apiResponse <- self$GetCalculationUnitResultByIdWithHttpInfo(id, unit.id, accept, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetCalculationUnitResultByIdWithHttpInfo = function(id, unit.id, accept=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        rlang::abort(message = "Missing required parameter `id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `id`."))
      }

      if (missing(`unit.id`)) {
        rlang::abort(message = "Missing required parameter `unit.id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `unit.id`."))
      }

      headerParams['Accept'] <- `accept`

      urlPath <- "/analytics/engines/spar/v3/calculations/{id}/units/{unitId}/result"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      if (!missing(`unit.id`)) {
        urlPath <- gsub(paste0("\\{", "unitId", "\\}"), URLencode(as.character(`unit.id`), reserved = TRUE), urlPath)
      }

      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ObjectRoot", loadNamespace("factset.analyticsapi.engines")),
          error = function(e){
             rlang::abort(message = "Failed to deserialize response", .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    },
    PostAndCalculate = function(x.fact.set.api.long.running.deadline=NULL, cache.control=NULL, spar.calculation.parameters.root=NULL, ...){
      apiResponse <- self$PostAndCalculateWithHttpInfo(x.fact.set.api.long.running.deadline, cache.control, spar.calculation.parameters.root, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    PostAndCalculateWithHttpInfo = function(x.fact.set.api.long.running.deadline=NULL, cache.control=NULL, spar.calculation.parameters.root=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      headerParams['X-FactSet-Api-Long-Running-Deadline'] <- `x.fact.set.api.long.running.deadline`

      headerParams['Cache-Control'] <- `cache.control`

      if (!missing(`spar.calculation.parameters.root`)) {
        body <- `spar.calculation.parameters.root`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/analytics/engines/spar/v3/calculations"
      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "CalculationStatusRoot", loadNamespace("factset.analyticsapi.engines")),
          error = function(e){
             rlang::abort(message = "Failed to deserialize response", .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    },
    PutAndCalculate = function(id, x.fact.set.api.long.running.deadline=NULL, cache.control=NULL, spar.calculation.parameters.root=NULL, ...){
      apiResponse <- self$PutAndCalculateWithHttpInfo(id, x.fact.set.api.long.running.deadline, cache.control, spar.calculation.parameters.root, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    PutAndCalculateWithHttpInfo = function(id, x.fact.set.api.long.running.deadline=NULL, cache.control=NULL, spar.calculation.parameters.root=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        rlang::abort(message = "Missing required parameter `id`.", .subclass = "ApiException", ApiException = ApiException$new(status = 0, reason = "Missing required parameter `id`."))
      }

      headerParams['X-FactSet-Api-Long-Running-Deadline'] <- `x.fact.set.api.long.running.deadline`

      headerParams['Cache-Control'] <- `cache.control`

      if (!missing(`spar.calculation.parameters.root`)) {
        body <- `spar.calculation.parameters.root`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/analytics/engines/spar/v3/calculations/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      # HTTP basic auth
      headerParams['Authorization'] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$apiClient$username, self$apiClient$password, sep=":"))))

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "CalculationStatusRoot", loadNamespace("factset.analyticsapi.engines")),
          error = function(e){
             rlang::abort(message = "Failed to deserialize response", .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- paste("Server returned " , httr::status_code(resp) , " response status code.")
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api client exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        errorMsg <- toString(content(resp))
        if(errorMsg == ""){
          errorMsg <- "Api server exception encountered."
        }
        rlang::abort(message = errorMsg, .subclass = "ApiException", ApiException = ApiException$new(http_response = resp))
      }
    }
  )
)
