# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StrategyOverrides
#' @description StrategyOverrides Class
#' @format An \code{R6Class} generator object
#' @field objective  character [optional]
#'
#' @field constraints  named list( character ) [optional]
#'
#' @field alpha  character [optional]
#'
#' @field transactioncost  character [optional]
#'
#' @field tax  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StrategyOverrides <- R6::R6Class(
  'StrategyOverrides',
  public = list(
    `objective` = NULL,
    `constraints` = NULL,
    `alpha` = NULL,
    `transactioncost` = NULL,
    `tax` = NULL,
    initialize = function(`objective`=NULL, `constraints`=NULL, `alpha`=NULL, `transactioncost`=NULL, `tax`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`objective`)) {
        stopifnot(is.character(`objective`), length(`objective`) == 1)
        self$`objective` <- `objective`
      }
      if (!is.null(`constraints`)) {
        stopifnot(is.vector(`constraints`), length(`constraints`) != 0)
        sapply(`constraints`, function(x) stopifnot(is.character(x)))
        self$`constraints` <- `constraints`
      }
      if (!is.null(`alpha`)) {
        stopifnot(is.character(`alpha`), length(`alpha`) == 1)
        self$`alpha` <- `alpha`
      }
      if (!is.null(`transactioncost`)) {
        stopifnot(is.character(`transactioncost`), length(`transactioncost`) == 1)
        self$`transactioncost` <- `transactioncost`
      }
      if (!is.null(`tax`)) {
        stopifnot(is.character(`tax`), length(`tax`) == 1)
        self$`tax` <- `tax`
      }
    },
    toJSON = function() {
      StrategyOverridesObject <- list()
      if (!is.null(self$`objective`)) {
        StrategyOverridesObject[['objective']] <-
          self$`objective`
      }
      if (!is.null(self$`constraints`)) {
        StrategyOverridesObject[['constraints']] <-
          self$`constraints`
      }
      if (!is.null(self$`alpha`)) {
        StrategyOverridesObject[['alpha']] <-
          self$`alpha`
      }
      if (!is.null(self$`transactioncost`)) {
        StrategyOverridesObject[['transactioncost']] <-
          self$`transactioncost`
      }
      if (!is.null(self$`tax`)) {
        StrategyOverridesObject[['tax']] <-
          self$`tax`
      }

      StrategyOverridesObject
    },
    fromJSON = function(StrategyOverridesJson) {
      StrategyOverridesObject <- jsonlite::fromJSON(StrategyOverridesJson)
      if (!is.null(StrategyOverridesObject$`objective`)) {
        self$`objective` <- StrategyOverridesObject$`objective`
      }
      if (!is.null(StrategyOverridesObject$`constraints`)) {
        self$`constraints` <- ApiClient$new()$deserializeObj(StrategyOverridesObject$`constraints`, "map(character)", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(StrategyOverridesObject$`alpha`)) {
        self$`alpha` <- StrategyOverridesObject$`alpha`
      }
      if (!is.null(StrategyOverridesObject$`transactioncost`)) {
        self$`transactioncost` <- StrategyOverridesObject$`transactioncost`
      }
      if (!is.null(StrategyOverridesObject$`tax`)) {
        self$`tax` <- StrategyOverridesObject$`tax`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`objective`)) {
        sprintf(
        '"objective":
          "%s"
                ',
        self$`objective`
        )},
        if (!is.null(self$`constraints`)) {
        sprintf(
        '"constraints":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`constraints`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`alpha`)) {
        sprintf(
        '"alpha":
          "%s"
                ',
        self$`alpha`
        )},
        if (!is.null(self$`transactioncost`)) {
        sprintf(
        '"transactioncost":
          "%s"
                ',
        self$`transactioncost`
        )},
        if (!is.null(self$`tax`)) {
        sprintf(
        '"tax":
          "%s"
                ',
        self$`tax`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StrategyOverridesJson) {
      StrategyOverridesObject <- jsonlite::fromJSON(StrategyOverridesJson)
      self$`objective` <- StrategyOverridesObject$`objective`
      self$`constraints` <- ApiClient$new()$deserializeObj(StrategyOverridesObject$`constraints`, "map(character)", loadNamespace("factset.analyticsapi.engines"))
      self$`alpha` <- StrategyOverridesObject$`alpha`
      self$`transactioncost` <- StrategyOverridesObject$`transactioncost`
      self$`tax` <- StrategyOverridesObject$`tax`
      self
    }
  )
)
