# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Strategy
#' @description Strategy Class
#' @format An \code{R6Class} generator object
#' @field id  character 
#'
#' @field overrides  \link{StrategyOverrides} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Strategy <- R6::R6Class(
  'Strategy',
  public = list(
    `id` = NULL,
    `overrides` = NULL,
    initialize = function(`id`, `overrides`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`overrides`)) {
        stopifnot(R6::is.R6(`overrides`))
        self$`overrides` <- `overrides`
      }
    },
    toJSON = function() {
      StrategyObject <- list()
      if (!is.null(self$`id`)) {
        StrategyObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`overrides`)) {
        StrategyObject[['overrides']] <-
          self$`overrides`$toJSON()
      }

      StrategyObject
    },
    fromJSON = function(StrategyJson) {
      StrategyObject <- jsonlite::fromJSON(StrategyJson)
      if (!is.null(StrategyObject$`id`)) {
        self$`id` <- StrategyObject$`id`
      }
      if (!is.null(StrategyObject$`overrides`)) {
        overridesObject <- StrategyOverrides$new()
        overridesObject$fromJSON(jsonlite::toJSON(StrategyObject$overrides, auto_unbox = TRUE, digits = NA))
        self$`overrides` <- overridesObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`overrides`)) {
        sprintf(
        '"overrides":
        %s
        ',
        jsonlite::toJSON(self$`overrides`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StrategyJson) {
      StrategyObject <- jsonlite::fromJSON(StrategyJson)
      self$`id` <- StrategyObject$`id`
      self$`overrides` <- StrategyOverrides$new()$fromJSON(jsonlite::toJSON(StrategyObject$overrides, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
