# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VaultComponentRoot
#' @description VaultComponentRoot Class
#' @format An \code{R6Class} generator object
#' @field data  \link{VaultComponent} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VaultComponentRoot <- R6::R6Class(
  'VaultComponentRoot',
  public = list(
    `data` = NULL,
    initialize = function(`data`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      VaultComponentRootObject <- list()
      if (!is.null(self$`data`)) {
        VaultComponentRootObject[['data']] <-
          self$`data`$toJSON()
      }

      VaultComponentRootObject
    },
    fromJSON = function(VaultComponentRootJson) {
      VaultComponentRootObject <- jsonlite::fromJSON(VaultComponentRootJson)
      if (!is.null(VaultComponentRootObject$`data`)) {
        dataObject <- VaultComponent$new()
        dataObject$fromJSON(jsonlite::toJSON(VaultComponentRootObject$data, auto_unbox = TRUE, digits = NA))
        self$`data` <- dataObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
        ',
        jsonlite::toJSON(self$`data`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VaultComponentRootJson) {
      VaultComponentRootObject <- jsonlite::fromJSON(VaultComponentRootJson)
      self$`data` <- VaultComponent$new()$fromJSON(jsonlite::toJSON(VaultComponentRootObject$data, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
