# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VaultCalculationParameters
#' @description VaultCalculationParameters Class
#' @format An \code{R6Class} generator object
#' @field componentid  character 
#'
#' @field account  \link{VaultIdentifier} 
#'
#' @field dates  \link{VaultDateParameters} [optional]
#'
#' @field configid  character 
#'
#' @field componentdetail  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VaultCalculationParameters <- R6::R6Class(
  'VaultCalculationParameters',
  public = list(
    `componentid` = NULL,
    `account` = NULL,
    `dates` = NULL,
    `configid` = NULL,
    `componentdetail` = NULL,
    initialize = function(`componentid`, `account`, `configid`, `dates`=NULL, `componentdetail`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`componentid`)) {
        stopifnot(is.character(`componentid`), length(`componentid`) == 1)
        self$`componentid` <- `componentid`
      }
      if (!missing(`account`)) {
        stopifnot(R6::is.R6(`account`))
        self$`account` <- `account`
      }
      if (!missing(`configid`)) {
        stopifnot(is.character(`configid`), length(`configid`) == 1)
        self$`configid` <- `configid`
      }
      if (!is.null(`dates`)) {
        stopifnot(R6::is.R6(`dates`))
        self$`dates` <- `dates`
      }
      if (!is.null(`componentdetail`)) {
        stopifnot(is.character(`componentdetail`), length(`componentdetail`) == 1)
        self$`componentdetail` <- `componentdetail`
      }
    },
    toJSON = function() {
      VaultCalculationParametersObject <- list()
      if (!is.null(self$`componentid`)) {
        VaultCalculationParametersObject[['componentid']] <-
          self$`componentid`
      }
      if (!is.null(self$`account`)) {
        VaultCalculationParametersObject[['account']] <-
          self$`account`$toJSON()
      }
      if (!is.null(self$`dates`)) {
        VaultCalculationParametersObject[['dates']] <-
          self$`dates`$toJSON()
      }
      if (!is.null(self$`configid`)) {
        VaultCalculationParametersObject[['configid']] <-
          self$`configid`
      }
      if (!is.null(self$`componentdetail`)) {
        VaultCalculationParametersObject[['componentdetail']] <-
          self$`componentdetail`
      }

      VaultCalculationParametersObject
    },
    fromJSON = function(VaultCalculationParametersJson) {
      VaultCalculationParametersObject <- jsonlite::fromJSON(VaultCalculationParametersJson)
      if (!is.null(VaultCalculationParametersObject$`componentid`)) {
        self$`componentid` <- VaultCalculationParametersObject$`componentid`
      }
      if (!is.null(VaultCalculationParametersObject$`account`)) {
        accountObject <- VaultIdentifier$new()
        accountObject$fromJSON(jsonlite::toJSON(VaultCalculationParametersObject$account, auto_unbox = TRUE, digits = NA))
        self$`account` <- accountObject
      }
      if (!is.null(VaultCalculationParametersObject$`dates`)) {
        datesObject <- VaultDateParameters$new()
        datesObject$fromJSON(jsonlite::toJSON(VaultCalculationParametersObject$dates, auto_unbox = TRUE, digits = NA))
        self$`dates` <- datesObject
      }
      if (!is.null(VaultCalculationParametersObject$`configid`)) {
        self$`configid` <- VaultCalculationParametersObject$`configid`
      }
      if (!is.null(VaultCalculationParametersObject$`componentdetail`)) {
        self$`componentdetail` <- VaultCalculationParametersObject$`componentdetail`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`componentid`)) {
        sprintf(
        '"componentid":
          "%s"
                ',
        self$`componentid`
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
        %s
        ',
        jsonlite::toJSON(self$`account`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`dates`)) {
        sprintf(
        '"dates":
        %s
        ',
        jsonlite::toJSON(self$`dates`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`configid`)) {
        sprintf(
        '"configid":
          "%s"
                ',
        self$`configid`
        )},
        if (!is.null(self$`componentdetail`)) {
        sprintf(
        '"componentdetail":
          "%s"
                ',
        self$`componentdetail`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VaultCalculationParametersJson) {
      VaultCalculationParametersObject <- jsonlite::fromJSON(VaultCalculationParametersJson)
      self$`componentid` <- VaultCalculationParametersObject$`componentid`
      self$`account` <- VaultIdentifier$new()$fromJSON(jsonlite::toJSON(VaultCalculationParametersObject$account, auto_unbox = TRUE, digits = NA))
      self$`dates` <- VaultDateParameters$new()$fromJSON(jsonlite::toJSON(VaultCalculationParametersObject$dates, auto_unbox = TRUE, digits = NA))
      self$`configid` <- VaultCalculationParametersObject$`configid`
      self$`componentdetail` <- VaultCalculationParametersObject$`componentdetail`
      self
    }
  )
)
