# Engines API
#
# Allow clients to fetch Analytics through APIs.
#
# The version of the OpenAPI document: v3:[pa,spar,vault,pub,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
# Contact: analytics.api.support@factset.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VaultCalculationParametersRoot
#' @description VaultCalculationParametersRoot Class
#' @format An \code{R6Class} generator object
#' @field data  named list( \link{VaultCalculationParameters} ) [optional]
#'
#' @field meta  \link{CalculationMeta} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VaultCalculationParametersRoot <- R6::R6Class(
  'VaultCalculationParametersRoot',
  public = list(
    `data` = NULL,
    `meta` = NULL,
    initialize = function(`data`=NULL, `meta`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
      if (!is.null(`meta`)) {
        stopifnot(R6::is.R6(`meta`))
        self$`meta` <- `meta`
      }
    },
    toJSON = function() {
      VaultCalculationParametersRootObject <- list()
      if (!is.null(self$`data`)) {
        VaultCalculationParametersRootObject[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }
      if (!is.null(self$`meta`)) {
        VaultCalculationParametersRootObject[['meta']] <-
          self$`meta`$toJSON()
      }

      VaultCalculationParametersRootObject
    },
    fromJSON = function(VaultCalculationParametersRootJson) {
      VaultCalculationParametersRootObject <- jsonlite::fromJSON(VaultCalculationParametersRootJson)
      if (!is.null(VaultCalculationParametersRootObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(VaultCalculationParametersRootObject$`data`, "map(VaultCalculationParameters)", loadNamespace("factset.analyticsapi.engines"))
      }
      if (!is.null(VaultCalculationParametersRootObject$`meta`)) {
        metaObject <- CalculationMeta$new()
        metaObject$fromJSON(jsonlite::toJSON(VaultCalculationParametersRootObject$meta, auto_unbox = TRUE, digits = NA))
        self$`meta` <- metaObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
',
        jsonlite::toJSON(lapply(self$`data`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
        %s
        ',
        jsonlite::toJSON(self$`meta`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VaultCalculationParametersRootJson) {
      VaultCalculationParametersRootObject <- jsonlite::fromJSON(VaultCalculationParametersRootJson)
      self$`data` <- ApiClient$new()$deserializeObj(VaultCalculationParametersRootObject$`data`, "map(VaultCalculationParameters)", loadNamespace("factset.analyticsapi.engines"))
      self$`meta` <- CalculationMeta$new()$fromJSON(jsonlite::toJSON(VaultCalculationParametersRootObject$meta, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
